#!/usr/bin/env python3
"""Regenerate bench/webui-routes.txt from a live opencode web bundle.

Usage:
    bench/webui/extract-routes.py <app-bundle.js> > bench/webui-routes.txt

The web UI's generated SDK embeds its route surface as either
`method:"get",path:"/x"` pairs or `.get({url:"/x"})` call sites. We extract
both and dedupe. This is the authoritative list for check-guards rule 15
(method-aware route binding) — the SDK list in bench/sdk-routes.txt is a
weaker, older, method-blind subset.
"""
import re
import sys


def extract(text: str) -> list[tuple[str, str]]:
    pairs: set[tuple[str, str]] = set()
    for m in re.finditer(r'method:"(get|post|put|delete|patch)",path:"([^"]+)"', text):
        pairs.add((m.group(1).upper(), m.group(2)))
    for m in re.finditer(r'\.(get|post|put|delete|patch)\(\{url:"([^"]+)"', text):
        pairs.add((m.group(1).upper(), m.group(2)))
    return sorted(pairs, key=lambda x: (x[1], x[0]))


def main() -> None:
    if len(sys.argv) != 2:
        sys.exit("usage: extract-routes.py <app-bundle.js>")
    text = open(sys.argv[1], encoding="utf-8", errors="replace").read()
    rows = extract(text)
    sys.stdout.write(
        "# Web-UI route inventory — extracted from the live opencode web bundle\n"
        "# (app-bundle.js served through ocserve's UI proxy).\n"
        "# Format: METHOD<space>PATH. Generated by bench/webui/extract-routes.py.\n"
        "# Used by scripts/check-guards.sh rule 15 (method-aware route binding).\n"
    )
    for meth, path in rows:
        sys.stdout.write(f"{meth} {path}\n")


if __name__ == "__main__":
    main()
