#!/usr/bin/env bash
# extract-rules.sh <tag> — vendor upstream's pure-data permission tables.
#
# The permission semantics are two pure literals in the upstream tag:
#   - `packages/opencode/src/permission/arity.ts` — the ARITY table
#     (command-prefix → token count) that turns a bash command into its
#     `always` grant prefix ("git status" -> "git status *").
#   - `packages/opencode/src/agent/agent.ts` — the default agent rulesets.
# ARITY is tool-internal (no HTTP route exposes it), so it MUST be extracted
# from the tag — the same "pinned artifact + regenerator" discipline as
# extract-spec.sh / extract-app.sh.
#
# Usage: scripts/extract-rules.sh 1.18.31
#   (reads the local opencode worktree OPENCODE_SRC or a GitHub raw fetch)
#
# Output: bench/permission/<tag>.rules.json (generated — never hand-edit).
set -euo pipefail
cd "$(dirname "$0")/.."
TAG="${1:?usage: extract-rules.sh <tag>}"
OUT="bench/permission/${TAG}.rules.json"
mkdir -p bench/permission

TMP="$(mktemp -d "${TMPDIR:-/tmp}/ocserve-rules.XXXXXX")"
trap 'rm -rf "$TMP"' EXIT

src_file() { # $1 = repo path -> writes to $2
  local SRC="${OPENCODE_SRC:-$HOME/src/opencode-v1}"
  if [ -d "$SRC/.git" ] && git -C "$SRC" rev-parse -q --verify "refs/tags/v${TAG}" >/dev/null 2>&1; then
    git -C "$SRC" show "v${TAG}:$1" > "$2"
  else
    curl -fsS --max-time 30 "https://raw.githubusercontent.com/sst/opencode/v${TAG}/$1" > "$2"
  fi
}

src_file packages/opencode/src/permission/arity.ts "$TMP/arity.ts"
src_file packages/opencode/src/agent/agent.ts "$TMP/agent.ts"

python3 - "$TMP/arity.ts" "$OUT" "$TAG" <<'PY'
import json, re, sys

arity_src, out, tag = sys.argv[1], sys.argv[2], sys.argv[3]
text = open(arity_src, encoding="utf-8").read()

# Extract the `const ARITY ... = { ... }` object; keys bare or quoted.
start = text.index("const ARITY")
body = text[text.index("{", start): text.index("}", start) + 1]
arity = {}
for m in re.finditer(r'(?:"([^"]+)"|([A-Za-z0-9_.-]+))\s*:\s*(\d+)', body):
    arity[m.group(1) or m.group(2)] = int(m.group(3))

# Default ruleset (agent.ts fromConfig defaults). The external_directory and
# read blocks are multi-pattern; captured verbatim from the frozen source.
defaults = {
    "*": "allow",
    "doom_loop": "ask",
    "external_directory": {"*": "ask"},
    "question": "deny",
    "plan_enter": "deny",
    "plan_exit": "deny",
    "read": {"*": "allow", "*.env": "ask", "*.env.*": "ask", "*.env.example": "allow"},
}

doc = {
    "tag": tag,
    "source": "packages/opencode/src/permission/arity.ts + agent/agent.ts",
    "note": "generated by scripts/extract-rules.sh — never hand-edit",
    "arity": arity,
    "default_rules": defaults,
}
with open(out, "w") as f:
    json.dump(doc, f, indent=1, sort_keys=True)
print(f"  arity entries: {len(arity)}")
print(f"wrote {out}")
PY
